# dataset
mode: dataprep_PPSCM_Apo
input_ref_filepath: /home/yuyang/Project_local/ProBiSEnSe/dataset/PPSCM_OMB/PPS_OMB_min_cg_pl.gro
ref_ligname: 2OW

traj_name: MD3
input_top_filepath: /home/yuyang/Project_local/ProBiSEnSe/dataset/PPSCM_Apo/PPS_Apo_min_cg_p.pdb
input_traj_filepath: /home/yuyang/Project_local/ProBiSEnSe/dataset/PPSCM_Apo/MD3/PPS_Apo_eq_md_T300_300ns_p_fit_skip100.xtc
output_aux_filepath: /home/yuyang/Project_local/ProBiSEnSe/temp/PPSCM_Apo/pocket_aux.txt
output_path: /home/yuyang/Project_local/ProBiSEnSe/temp/PPSCM_Apo/MD3
frames_list: [0,1,2,3,4,5,6,7]

# parameters
ligand_aa_dist: 5  # amino acids within 5 Å to atoms of ligand to be considered in the pocket
aligned_sele_wo_hydrogen: False  # if True, align the pocket without hydrogen atoms
dist_threshold_to_heavy_atom: 5  # points within 5 Å to the heavy atoms of ligand to be considered to be labeled
radius_for_grid: 16 # radius for grid of interest
spacing: 0.5  # grid spacing

# parallel processing
max_workers: 8

# debug
debug: False